language: r
warnings_are_errors: false
cache:
  packages: true
after_success:
- curl -OL http://raw.githubusercontent.com/soztag/fau_deploy/master/deploy2karli.sh
deploy:
- provider: script
  skip_cleanup: true
  script:
  - bash deploy2karli.sh
  on:
    branch: master
notifications:
  email: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_8dfc592ec87f_key -iv $encrypted_8dfc592ec87f_iv
  -in karli_rsa.enc -out /tmp/karli_rsa -d
