---
title: "Syllabus"
author:
  name: "Maximilian Held"
  affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: library.bib
---

<div class="jumbotron" style="color:white; background: linear-gradient( rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7) ), url(img/q-sorting2.jpg) no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
  <h2>Q Methodology as a Deliberative Technology</h1>
  <p>... the next best thing to a personal conversation?</p>
  <p>
    <span class="label label-info">
      #qdelib
    </span>
  </p>
  <p><small><sub>
    Image Credit: [CiviCon](http://www.civicon.de) participants completing a Q-Sort &copy; [Max Held](http://www.maxheld.de) 2014
  </sub></small></p>
</div>

```{r, child="README.Rmd"}
```

---

> *Reaching understanding is the inherent telos of human speech.*  
> --- Jürgen @Habermas-1984 [: 33]
 
> *Operational definitions begin with concepts in search of behavior; operant definitions begin with behavior in search of concepts.*  
> --- Steven @Brown1980 [: 28]

## Course Description

Q is an approach for the scientific study of human subjectivity, including a methodology, a special survey technique (the Q-Sort) and custom statistical analyses. 
It dates back to the beginnings of psychometry [@Stephenson1935a], and has since attracted a small, but scrappy following and spawned applications in many disciplines, including sociology, political science, public health and psychology. 

In a Q study, participants weigh and rank-order a larger number of typically open-ended, longer or complex items carefully selected by the researchers. 
The sorts of all participants are then statistically summarised into a few shared sorting patterns, and the resulting “ideal types” of shared subjectivity are thoroughly interpreted.

Compared to conventional survey research, Q methodology promises to deliver a more inductive, explorative and holistic understanding of human subjectivity more akin to qualitative approaches, but its statistical component also allows some quantitative rigor. 
Not as a mixed, but as a two-step method, Q thus combines aspects of qualitative and quantitative research.

The seminar proceeds along the steps of a complete Q study, including concourse generation, item sampling, sorting procedure, factor retention and extraction, rotation, scoring and interpretation. 
We engage old controversies in each of these steps and learn about new statistical approaches, many of which are implemented in the pensieve R software developed at FAU. 
Students will also compare Q methodology to conventional “R-mode” survey research, though less because this dichotomy is to be taken as gospel, but to highlight the tradeoffs, limits and contradictions of any methodology, and to inform an epistemologically pragmatic choice.

Finally, Q is suggested as a method to measure and enhance deliberative participation, with a special focus on subjective experiences in the workplace. 
We will draw parallels between Q methodology and deliberative theory, assess the usefulness of sorting as a participation tool, and consider quantitative measures of deliberative quality.

Q, as any research methodology, is strictly limited by the time and effort invested by researchers and participants, and requires a suitable context and research question. 
Yet, in a world of big, but sometimes meaningless data, burgeoning filter bubbles and occasionally reductionistic survey research, Q offers something rare: to systematically expose people to new ideas, to carefully record their interaction, and to faithfully interpret the resulting viewpoints in their own terms.

The regulative ideal of Q, then, is something simple, yet hard to come by in our time: deep, mutual understanding, as it might be reached after a thoughtful discussion with a trusted but dissenting friend. 
Such communicative action in the lifeworld, is, alas, always threatened by our noisy systems and, in any case, does not “scale” very well. 
Q might just be the next best thing we have; a humble and imperfect tool to engage each others subjectivity.

Participants will conduct a small Q study of their own design, using specialised software and open source tools for collaboration.


## Prerequisites {.alert .alert-info}

*Everyone* is welcome to this seminar.

There are no hard prerequisites to fulfil, though participants are expected to:

- read and discuss academic texts in English, as well as write in english,
- catch up on basic descriptive statistics (the method is both qualitative and quantitative)
- learn to use specialised command-line software and open-source tools for collaboration.

No worries, we'll bring everyone up to speed in no time.


## Venue {.alert .alert-warning}

Classes will take place in one of two FAU locations:

IFS

: 
    <address>
    | Institut für Soziologie
    | Room 5052
    | Kochstraße 4
    | 91054 Erlangen
    </address>

NCT

: 
    <address>
    | Nuremberg Campus of Technology
    | "Auf AEG" Haus 11
    | Room 11.2.2
    | Fürther Straße 246c
    | 90429 Nuremberg
    </address>
    
    (The building can be hard to find; see [here](http://www.ncatec.de/nct/wir-ueber-uns/lageplan.html) for directions).


## Material {.well}

All *mandatory* course material (readings) will be either

- freely available online, 
- on [StudOn](https://www.studon.fau.de/),
- (if copyright restrictions do not permit otherwise) available on the course reserve collection ("Semesterapparat") at the IFS library.

In *addition*, recommended material may also be available in these places, but you do not *have* to read it.

Please consult the below schedule for the mandatory readings.

## Schedule

### Introduction

<span class="label label-primary">Thursday, April 12, 2018 14:15--15:45</span>
<span class="label label-default">IFS</span>
<span class="label label-success">No Readings</span>

#### Recommended Readings

- @Exel2005 [, `@Exel2005`]


### Doing a Q-Sort

<span class="label label-primary">Thursday, April 19, 2018 14:15--15:45</span>
<span class="label label-default">NCT</span>
<span class="label label-success">No Readings</span>


### Designing our own Q-Study

<span class="label label-primary">Friday, May 25, 2018 09:00-18:00</span>
<span class="label label-default">NCT</span>
<span class="label label-warning">Bring Your Computer</span>
<span class="label label-info">All Day</span>

During this session, we conceive of our own Q research design, based on selected theoretical and methodological foundations.

| Time | Topic | Mandatory Reading |
|-------|---------------------------------|-------------------|
| 09:00 | Results from April 19 |  |
| 10:00 | Theory I: Discourse Ethics | @Habermas-1998-aa [, `@Habermas-1998-aa`] |
| 12:00 | Theory II: Operant Subjectivity | @brown-1993-a [, @brown-1993-a], @Watts2012 [`Watts2012`, Chapters 1--3, only available at IFS library course reserve aka. "Semesterapparat"] |
| 14:00 | Defining our Q Study Topic |  |
| 15:00 | Methodology I: Creating Good Q-Items | @BakerConstructingStatementSets2017 [`@BakerConstructingStatementSets2017`] |
| 17:00 | Preparing Q-Items | |


#### Field Work {.alert .alert-warning}

Between this session (May 25) and the next one (June 22), you are expected to conduct **10** Q-Sorts with willing participants, **2** of which you should complete *in person*.
Recruiting participants can take some time, and so does administering a Q-Sort, especially in person.
Plan accordingly.

The detailed deadlines are:

- Tuesday, May 29: add and revise items (we need > 60 without duplicates).
- Tuesday, May 29: vote on your preferred items (right now, it does not look like we will have more than absolutely needed anyway).
- Wednesday, May 30: Translate "your" items into german.
- Saturday, June 2: Receive Item Packets in your mail
- Wednesday, June 13: Complete at least **2** in-person Q-Sorts by this point (to check whether how we're doing). *Briefly report the experience to Max*.
- Thursday, June 14: Backup Qmethod meeting, in case things didn't go well.
- Thursday, June 21: Gather remaining Q-Sorts in person (preferable) or online.
  All participants need to contribute at least **10** Q-Sorts.

Remember to sample a *diverse* group of people in terms of demographics (age, income, gender) and with regard to the chosen topic.


### Backup Date

<span class="label label-primary">Thursday, June 14, 2018 14:00-16:00</span>
<span class="label label-default">IFS</span>
<span class="label label-info">Optional</span>

(If things go badly in the field.)


### Learning the Tools (FOSS and PCA)

<span class="label label-primary">Friday, June 22, 2018 09:00-18:00</span>
<span class="label label-default">NCT</span>
<span class="label label-warning">Bring Your Computer</span>
<span class="label label-info">All Day</span>


<div class="alert alert-warning">
Remember to **bring and update your computer**.
Specifically:

- Have a current version of the [Chrome](https://www.google.com/chrome/) or [Firefox](https://www.firefox.com) web browsers installed.
- Make sure that your WiFi works.
  At NCT, we have `FAU-STUD`, `eduroam` and `FAU.fm`.
  If you need help setting up your WiFi, consult the [RRZE Website](https://www.rrze.fau.de).
- Bring your power adapter.
- A mobile device (iOS or Android tablet) *will not suffice*.
  You need a laptop, but pretty much any (cheap or old) device will be fine, if it can run the above browsers in a current version.
- If you do not have access to a laptop, please contact the course instructor (me) in advance, and we'll arrange a device for you.
</div>

During this session, we learn the tools we need to analyse our results and to collaborate on our report.

| Time | Topic | Mandatory Reading |
|-------|---------------------------------|-------------------|
| 09:00 | Pandoc Markdown | [Pandoc Markdown](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html) |
| 10:00 | Git(hub) | [GitHub Guides](https://guides.github.com), [Try Git](https://try.github.io/), [git documentation](https://git-scm.com/doc) (optional, browse only)|
| 15:00 | Methodology II: PCA | @Thompson-2004 [: Chapters 1--3, `@Thompson-2004`] |


#### Optional Installations

If you'd like to be able to use more advanced tools for analysis, editing and compiling on *your own* computer, feel free to install these.

- [Pandoc, a universal document converter](https://pandoc.org)
- [LaTeX Typsetting System](https://www.latex-project.org)
- [git decentralized source control management (SCM)](https://git-scm.com)
- [R Project for Statistical Computing](Statisticalhttps://www.r-project.org)
- [RStudio R Integrated Development Environment (IDE)](https://www.rstudio.com/products/RStudio/)
- A bunch of R packages:
  - [tidyverse](https://www.tidyverse.org)
  - [rmarkdown](https://rmarkdown.rstudio.com)
  - [pensieve](https://pensieve.maxheld.de)

The steps required for installation will depend on your platform and system setup.
Please understand that we cannot support or troubleshoot these installations during class, but you will find ample resources on the internet.

In any event, you will *not need* to use this software on your computer.
To save time, we will rely on web-based alternatives wherever possible.


### Analysing our Results

<span class="label label-primary">Saturday, June 23, 2018 09:00-18:00</span>
<span class="label label-default">NCT</span>
<span class="label label-warning">Bring Your Computer</span>
<span class="label label-warning">Bring Food (cafeteria closed)</span>
<span class="label label-info">All Day</span>

During this session, we interactively investigate our data and make analytical choices for our results.

| Time | Topic | Mandatory Reading |
|-------|---------------------------------|-------------------|
| 09:00 | Correlations | @Brown1980 [: Chapter 4, `@Brown1980`]  |
| 10:00 | Factor Extraction and Retention | |
| 11:00 | Factor Rotation (Loadings) | |
| 12:00 | Factor Scores | |
| 14:00 | Factor Interpretation | @Watts2012 [: Chapter 7, ` @Watts2012`] |
| 16:00 | Write-Up | |


### Interpretation and Review

<span class="label label-primary">Saturday, June 30, 2018 09:00-18:00</span>
<span class="label label-default">NCT</span>
<span class="label label-warning">Bring Your Computer</span>
<span class="label label-warning">Bring Food (cafeteria closed)</span>
<span class="label label-info">All Day</span>

During this session, we wrap up and reflect on our work.

| Time | Topic | Mandatory Reading |
|-------|---------------------------------|-------------------|
| 09:00 | Review of Write-Up | |
| 14:00 | Reflection | @Brown1980 [: Epilogue, 321ff, `@Brown1980`] |



## Assessment

Students who wish to receive a grade for the class (as opposed to a "Sitzschein" pass/fail option) must submit a written report of the Q study undertaken as part of the class, with due reference to the mandatory readings assigned.

*Alternatively*, students can submit a *partial* report, to be combined with other parts from other students.

There is no strict word limit, but students should expect to write at least around **2000 words** across their different contributions.
Anything beyond **4000 words** is probably not necessary.

The following grading rubric applies:

|  | Reasoning: **Conceptual** (20%) | Reasoning: **Thesis** (20%) | Reasoning: **Development  & Support**  (20%) | Reasoning: **Structuring** (20%) | Mechanics: **Rhetorical** (5%) | Mechanics: **Language** (5%) | Mechanics: **Technology** (10%) |
|-----------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Superior (1.00) | has cogent analysis, shows command of interpretive and conceptual tasks required by assignment and course materials: ideas original, often insightful, going beyond ideas discussed in lecture and class | essay controlled by clear, precise, well-defined argument; is sophisticated in both statement and insight | well-chosen examples; uses persuasive reasoning to develop and support thesis consistently; uses specific quotations, statistics, aesthetic details, or citations of scholarly sources effectively; logical connections between ideas are evident | well-constructed paragraphs; appropriate, clear and smooth transitions; arrangement of organizational elements seems particularly apt | commands attention with a convincing argument with a compelling purpose; highly responsive to the demands of a specific writing situation; sophisticated use of,conventions of academic discipline and genre; anticipates the reader's needs for information, explanation, and context | uses sophisticated sentences effectively; usually chooses words aptly; observes professional conventions of written English and manuscript format; makes few minor or technical errors | uses version control, markup and other software development best practices to strengthen presentation and reproducible research. |
| Good (2.00) | shows a good understanding of the texts, ideas and methods of the assignment; goes beyond the obvious; may have one minor factual or conceptual inconsistency | clear, specific, arguable central claims; may have left minor terms undefined | pursues explanation and proof of thesis consistently; develops a main argument with explicit major points with appropriate textual evidence and supporting detail | distinct units of thought in paragraphs controlled by specific, detailed, and arguable topic sentences; clear transitions between developed, cohering, and logically arranged paragraphs | addresses audience with a thoughtful argument with a clear purpose; responds directly to the demands of a specific writing situation; competent use of the conventions of academic discipline and genre; addresses the reader's needs for information, explanation, and context | a few mechanical difficulties or stylistic problems (which/that use, split infinitives, dangling modifiers, etc.); may make occasional problematic word choices or syntax errors; a few spelling or punctuation errors or a cliche; usually presents quotations effectively, using appropriate format | minor technical shortcomings still allow reproduction of research and effective collaboration |
| Satisfactory (3.00) | shows an understanding of the basic ideas and information involved in the assignment; may have some factual, interpretive, or conceptual errors | general thesis or controlling idea; may not define several central terms | only partially develops the argument; shallow analysis; some ideas and generalizations undeveloped or unsupported; makes limited use of textual or visual evidence; fails to integrate quotations appropriately | some awkward transitions; some brief, weakly unified or undeveloped paragraphs; arrangement may not appear entirely natural; contains extraneous information | presents an adequate response the essay prompt; pays attention to the basic elements of the writing situation; shows sufficient competence in the conventions of academic discipline and genre; signals the importance of the reader's needs for information, explanation, and context | more frequent wordiness; unclear or awkward sentences; imprecise use of words or over-reliance on passive voice; some distracting grammatical errors (wrong verb tense, pronoun agreement, apostrophe errors, singular/plural errors, article use, preposition use, comma splice, etc.); makes effort to present quotations accurately | tools are sometimes used inappropriately and best practices are not adhered to |
| Unsatisfactory (4.00) | shows inadequate command of course materials or has significant factual and conceptual errors; confuses some significant ideas | argument vague; central terms not defined | frequently only narrates; digresses from one topic to another without developing ideas or terms; makes insufficient or awkward use of textual or visual evidence; relies on too few or the wrong type of sources | simplistic, tends to narrate or merely summarize; wanders from one topic to another; illogical arrangement of ideas | shows serious weaknesses in addressing an audience; unresponsive to the specific writing situation; poor articulation of purpose; often states the obvious or the inappropriate | some major grammatical or proofreading errors (subject-verb agreement, sentence fragments, word form errors, etc.); language frequently weakened by colloquialisms, clichés, repeated inexact word choices; incorrect quotation or citation format | some major misuses and lapses hinder reproducibility and effective collaboration |
| Unacceptable (5.00) | writer lacks critical understanding of lectures, readings, discussions, or assignments | no discernible argument | little or no development; may list disjointed facts or misinformation; uses no quotations or fails to cite sources or plagiarizes | no transitions; incoherent paragraphs; suggests poor planning or no serious revision | shows severe difficulties communicating | numerous grammatical errors and stylistic problems seriously detract from the argument; does not meet Standard Written English requirement | severe lack of technical competency and consistency interfere with the quality of the research |


## Contact

Find my contact details [here](http://www.maxheld.de).


## Recommended Readings (Optional)

- @Habermas1996b
  - Chapter 7: Deliberative Politics
  - Chapter 4.2: Communicative Power and the Genesis of Law
  - Additionally: Chapters 3, 4, 7, 8, Preface
- @Habermas1994
- @Habermas-1984
  - Chapter III, 2-4
  - Chapter VI: 1
- @Brown1980
- @Good-1998
- @McKeown2013
- @Niemeyer2013
- @Paige-Morin-2014
- @stephenson-1935
- @Stephenson1953
- @Watts2012

## References
